name: CI/CD

on:
	push:
		branches:
			- main

jobs:
	build-and-deploy:
		runs-on: ubuntu-latest

		steps:
			# 1. GitHub 레포지토리 체크아웃
			- name: Checkout Repository
			  uses: actions/checkout@v3

			# 2. AWS CLI 자격증명 설정
			- name: Configure AWS Credentials
			  uses: aws-actions/configure-aws-credentials@v3
			  with:
				  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
				  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
				  aws-region: ap-northeast-2

			# 3. AWS ECR Docker 로그인
			- name: Docker Login to AWS ECR
			  id: login-ecr
			  uses: aws-actions/amazon-ecr-login@v2

			# 4. Docker 이미지 빌드 및 ECR 푸시
			- name: Build and Push Docker image to ECR
			  env:
				  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
				  ECR_REPOSITORY: pmsu2007/ktb-community
				  IMAGE_TAG: latest
			  run: |
				  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --platform linux/amd64 .
				  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

			# 5. EC2에서 deploy.sh 실행
			- name: Deploy to EC2
			  uses: appleboy/ssh-action@master
			  with:
				  host: ${{ secrets.EC2_HOST }}
				  username: ${{ secrets.EC2_USERNAME }}
				  port: 22
				  key: ${{ secrets.EC2_SSH_KEY }}
				  script: |
					  cd ~/app
					  ./deploy.sh